version: '3.5'
services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=TelegrafPassword
    volumes:
      - /srv/docker/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - backend
    labels:
      - "traefik.enable=false"
      - "container_group=TIG"
 
  telegraf:
    image: telegraf
    volumes:
      - $PWD/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /run:/rootfs/run:ro
      - /etc:/rootfs/etc:ro
    depends_on:
      - influxdb
    networks:
      - backend
    environment:
      HOST_PROC: '/rootfs/proc'
      HOST_SYS: '/rootfs/sys'
      HOST_ETC: '/rootfs/etc'
    labels:
      - "traefik.enable=false"
      - "container_group=TIG"
    deploy:
      mode: global
 
  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.zitrolab.lan
      - GF_SECURITY_ADMIN_PASSWORD=GrafanaPassword
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,raintank-worldping-app,jdbranham-diagram-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SERVER_DOMAIN=zitrolab.lan
    volumes:
      - /srv/docker/grafana:/var/lib/grafana
    networks:
      - proxy
      - backend
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=tick"
      - "traefik.frontend.rule=Host:grafana.zitrolab.lan"
      - "traefik.docker.network=proxy"
      - "traefik.port=3000"
      - "container_group=TIG"
 
networks:
  backend:
    driver: 'overlay'
  proxy:
    name: proxy
    external: true
 
volumes:
  grafana:
  influxdb:
